# Generated by Django 6.0.6 on 2026-06-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Tokunbo 2015 Toyota Camry or 4 Bedroom Bungalow', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated for SEO-optimized clean URLs', max_length=275, unique=True)),
                ('category', models.CharField(choices=[('property', 'Real Estate / Houses'), ('vehicle', 'Vehicles / Cars')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('region', models.CharField(help_text='e.g., Uyo, Akwa Ibom or Ikeja, Lagos', max_length=100)),
                ('google_map_url', models.URLField(blank=True, help_text='Direct link copied from Google Maps app', null=True)),
                ('description', models.TextField(help_text='Detailed description of features and condition')),
                ('main_image', models.ImageField(upload_to='listings/main/')),
                ('video_url', models.URLField(blank=True, help_text='Walkthrough tour video link (YouTube, TikTok, Reels)', null=True)),
                ('is_verified', models.BooleanField(default=True, help_text="Displays 'Verified by Cassie' trust badge")),
                ('is_approved', models.BooleanField(default=False, help_text='Gatekeeper flag. Only True items go live on public feed')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=15)),
                ('contact_phone', models.CharField(default='2348000000000', help_text="Cassie's WhatsApp/Call number with country code", max_length=20)),
                ('car_year', models.IntegerField(blank=True, help_text='For Cars Only', null=True)),
                ('car_transmission', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20, null=True)),
                ('house_bedrooms', models.IntegerField(blank=True, help_text='For Houses Only', null=True)),
                ('house_document', models.CharField(blank=True, help_text='For Houses Only: e.g., C of O, Survey Plan', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-status', '-created_at'],
            },
        ),
    ]
