# Generated by Django 6.0.6 on 2026-06-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='art_medium',
            field=models.CharField(blank=True, help_text='Fine Art Only: e.g., Oil on Canvas, Acrylic Painting, Mixed Media', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='car_year',
            field=models.IntegerField(blank=True, help_text='Vehicles Section Only', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('property', 'Real Estate / Houses'), ('vehicle', 'Vehicles / Cars'), ('art', 'Original Fine Art / Paintings')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(default='2348000000000', help_text="Cassie's phone number with country code (no spaces/special chars)", max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(help_text='Detailed description of features, paper status, or dimensions'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='google_map_url',
            field=models.URLField(blank=True, help_text='Direct link copied from Google Maps application', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_bedrooms',
            field=models.IntegerField(blank=True, help_text='Properties Section Only', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_document',
            field=models.CharField(blank=True, help_text='Properties Only: e.g., C of O, Survey Plan', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Gatekeeper flag: requires Lead Admin approval before going live'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='region',
            field=models.CharField(help_text='e.g., Osongama, Uyo or Lekki, Lagos', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated clean URL for localized SEO', max_length=275, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='e.g., Clean Tokunbo Lexus RX 350, 4 Bedroom Duplex, or Abstract Canvas Painting', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional walkthrough video tour link (YouTube, TikTok, Reels)', null=True),
        ),
    ]
