# Generated by Django 6.0.6 on 2026-06-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_listing_art_medium_alter_listing_car_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='land_size',
            field=models.CharField(blank=True, help_text='Land Only: e.g., 100ft x 100ft, 1 Full Plot, 3 Hectares', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('property', 'Real Estate / Houses'), ('vehicle', 'Vehicles / Cars'), ('art', 'Original Fine Art / Paintings'), ('land', 'Land & Acreage / Plots')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(default='2348148714875', help_text="Cassie's phone number with country code", max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_document',
            field=models.CharField(blank=True, help_text='Properties & Land Only: e.g., C of O, Survey Plan, Deed of Assignment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='e.g., Clean Tokunbo Lexus RX 350, 4 Bedroom Duplex, Abstract Canvas, or 2 Plots of Commercial Land', max_length=255),
        ),
    ]
