# Generated by Django 6.0.6 on 2026-06-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_listing_land_size_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='car_cracks_faults',
            field=models.TextField(blank=True, help_text='Specify any windshield cracks, body dents, engine faults, or mechanical diagnostics.', null=True, verbose_name='Vehicle Damage & Body Cracks Report'),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New / Pristine'), ('clean_tokunbo', 'Very Clean / Foreign Used (Tokunbo)'), ('locally_used', 'Locally Used / Minor Wear'), ('needs_work', 'Needs Minor Repairs')], default='clean_tokunbo', help_text='Physical assessment condition grading', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='house_condition_integrity',
            field=models.TextField(blank=True, help_text='Log any foundation settlement, wall cracks, water leaks, or renovation history.', null=True, verbose_name='Structural Integrity & Wall Cracks Assessment'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='art_medium',
            field=models.CharField(blank=True, help_text='For Fine Art Only: e.g., Oil on Canvas, Textured Acrylic', max_length=100, null=True, verbose_name='Artwork Medium/Materials'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='car_transmission',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20, null=True, verbose_name='Gearbox Transmission'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='car_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Manufacturing Year'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(default='2348148714875', help_text="Cassie's line with international prefix codes", max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(help_text='Detailed public marketing pitch summary'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='google_map_url',
            field=models.URLField(blank=True, help_text='Direct connection link copied from Google Maps app', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Bedrooms'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_document',
            field=models.CharField(blank=True, help_text='For Houses & Land Only: e.g., C of O, Registered Survey, Gazette', max_length=100, null=True, verbose_name='Legal Title Documentation'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Requires Lead Admin validation before public release'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='land_size',
            field=models.CharField(blank=True, help_text='For Land Only: e.g., 100ft x 100ft, 1 Full Plot', max_length=100, null=True, verbose_name='Land Area Measurements'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='e.g., Tokunbo 2018 Lexus RX 350 or 4 Bedroom Detached Duplex', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional link to walkthrough tour video', null=True),
        ),
    ]
