# Generated by Django 6.0.6 on 2026-06-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_listing_car_cracks_faults_listing_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='condition',
        ),
        migrations.AlterField(
            model_name='listing',
            name='art_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='car_cracks_faults',
            field=models.TextField(blank=True, null=True, verbose_name='Vehicle Damage & Body Cracks Report'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='car_transmission',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='car_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('property', 'Real Estate / Houses'), ('vehicle', 'Vehicles / Cars'), ('art', 'Original Fine Art / Paintings'), ('land', 'Land & Acreage / Plots')], default='property', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(default='2348148714875', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='google_map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_condition_integrity',
            field=models.TextField(blank=True, null=True, verbose_name='Structural Integrity & Wall Cracks Assessment'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_document',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Legal Title Documentation'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='land_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=275, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
