# Generated by Django 6.0.6 on 2026-06-07 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_listing_condition_alter_listing_art_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='suit_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Suit Material'),
        ),
        migrations.AddField(
            model_name='listing',
            name='suit_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Suit Size'),
        ),
        migrations.AddField(
            model_name='listing',
            name='suit_style',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Suit Style'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('suits', 'Suits'), ('soaked', 'Soaked'), ('property', 'Houses'), ('vehicle', 'Cars')], default='property', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(default='Anonymous', max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
