# Generated by Django 6.0.6 on 2026-06-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_pageview_trafficcounter_listing_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
